<a href="https://colab.research.google.com/github/KodumuruRaja/Feature-Selection/blob/main/Feature-Selection-(Recursive%20Feature%20Elimination%20(RFE)%20by%20Using%20Random%20Forest%20and%20Gradient%20Boosting%20Algorithm).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn.metrics import accuracy_score

In [ ]:
from sklearn.datasets import load_breast_cancer

In [ ]:
data=load_breast_cancer()

In [ ]:
data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [ ]:
data.DESCR

'.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 569\n\n    :Number of Attributes: 30 numeric, predictive attributes and the class\n\n    :Attribute Information:\n        - radius (mean of distances from center to points on the perimeter)\n        - texture (standard deviation of gray-scale values)\n        - perimeter\n        - area\n        - smoothness (local variation in radius lengths)\n        - compactness (perimeter^2 / area - 1.0)\n        - concavity (severity of concave portions of the contour)\n        - concave points (number of concave portions of the contour)\n        - symmetry \n        - fractal dimension ("coastline approximation" - 1)\n\n        The mean, standard error, and "worst" or largest (mean of the three\n        largest values) of these features were computed for each image,\n        resulting in 30 features.  For instance,

In [ ]:
x=pd.DataFrame(data=data.data,columns=data.feature_names)
x.head()

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0        17.99         10.38  ...          0.4601                  0.11890
1        20.57         17.77  ...          0.2750                  0.08902
2        19.69         21.25  ...          0.3613                  0.08758
3        11.42         20.38  ...          0.6638                  0.17300
4        20.29         14.34  ...          0.2364                  0.07678

[5 rows x 30 columns]

In [ ]:
y=data.target

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
x_train.shape,y_train.shape

((455, 30), (455,))

# **Feature Slection by feature importance of random forest classifier**

In [ ]:
sel=SelectFromModel(RandomForestClassifier(n_estimators=100,random_state=0,n_jobs=-1))
sel.fit(x_train,y_train)
sel.get_support()

array([ True, False,  True,  True, False, False,  True,  True, False,
       False, False, False, False,  True, False, False, False, False,
       False, False,  True, False,  True,  True, False, False, False,
        True, False, False])

In [ ]:
x_train.columns

Index(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error', 'fractal dimension error',
       'worst radius', 'worst texture', 'worst perimeter', 'worst area',
       'worst smoothness', 'worst compactness', 'worst concavity',
       'worst concave points', 'worst symmetry', 'worst fractal dimension'],
      dtype='object')

In [ ]:
features=x_train.columns[sel.get_support()]

In [ ]:
features

Index(['mean radius', 'mean perimeter', 'mean area', 'mean concavity',
       'mean concave points', 'area error', 'worst radius', 'worst perimeter',
       'worst area', 'worst concave points'],
      dtype='object')

In [ ]:
len(features)

10

In [ ]:
np.mean(sel.estimator_.feature_importances_)

0.03333333333333334

In [ ]:
sel.estimator_.feature_importances_

array([0.03699612, 0.01561296, 0.06016409, 0.0371452 , 0.0063401 ,
       0.00965994, 0.0798662 , 0.08669071, 0.00474992, 0.00417092,
       0.02407355, 0.00548033, 0.01254423, 0.03880038, 0.00379521,
       0.00435162, 0.00452503, 0.00556905, 0.00610635, 0.00528878,
       0.09556258, 0.01859305, 0.17205401, 0.05065305, 0.00943096,
       0.01565491, 0.02443166, 0.14202709, 0.00964898, 0.01001304])

In [ ]:
x_train_rfc=sel.transform(x_train)
x_test_rfc=sel.transform(x_test)

In [ ]:
def run(x_train,x_test,y_train,y_test):
  clf=RandomForestClassifier(n_estimators=100,random_state=0,n_jobs=-1)
  clf.fit(x_train,y_train)
  y_pred=clf.predict(x_test)
  print("Accuracy:",accuracy_score(y_test,y_pred))

In [ ]:
%%time
run(x_train_rfc,x_test_rfc,y_train,y_test)

Accuracy: 0.9473684210526315
CPU times: user 345 ms, sys: 64.3 ms, total: 409 ms
Wall time: 458 ms


In [ ]:
%%time
run(x_train,x_test,y_train,y_test)

Accuracy: 0.9649122807017544
CPU times: user 404 ms, sys: 58.4 ms, total: 463 ms
Wall time: 461 ms


# **Recursive Feature Elimination**

In [ ]:
from sklearn.feature_selection import RFE
sel=RFE(RandomForestClassifier(n_estimators=100,random_state=0,n_jobs=-1),n_features_to_select=15)
sel.fit(x_train,y_train)

RFE(estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                     class_weight=None, criterion='gini',
                                     max_depth=None, max_features='auto',
                                     max_leaf_nodes=None, max_samples=None,
                                     min_impurity_decrease=0.0,
                                     min_impurity_split=None,
                                     min_samples_leaf=1, min_samples_split=2,
                                     min_weight_fraction_leaf=0.0,
                                     n_estimators=100, n_jobs=-1,
                                     oob_score=False, random_state=0, verbose=0,
                                     warm_start=False),
    n_features_to_select=15, step=1, verbose=0)

In [ ]:
sel.get_support()

array([ True,  True,  True,  True, False, False,  True,  True, False,
       False, False, False, False,  True, False, False, False, False,
       False, False,  True,  True,  True,  True,  True, False,  True,
        True,  True, False])

In [ ]:
features=x_train.columns[sel.get_support()]

In [ ]:
features

Index(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean concavity', 'mean concave points', 'area error', 'worst radius',
       'worst texture', 'worst perimeter', 'worst area', 'worst smoothness',
       'worst concavity', 'worst concave points', 'worst symmetry'],
      dtype='object')

In [ ]:
len(features)

15

In [ ]:
x_train_rfe=sel.transform(x_train)
x_test_rfe=sel.transform(x_test)

In [ ]:
%%time
run(x_train_rfe,x_test_rfe,y_train,y_test)

Accuracy: 0.9736842105263158
CPU times: user 356 ms, sys: 52.2 ms, total: 408 ms
Wall time: 459 ms


In [ ]:
%%time
run(x_train,x_test,y_train,y_test)

Accuracy: 0.9649122807017544
CPU times: user 406 ms, sys: 48.3 ms, total: 454 ms
Wall time: 459 ms


# **Feature Selection by GradientBoost Tree Importance**

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

In [ ]:
sel=RFE(GradientBoostingClassifier(n_estimators=100,random_state=0),n_features_to_select=12)
sel.fit(x_train,y_train)

RFE(estimator=GradientBoostingClassifier(ccp_alpha=0.0,
                                         criterion='friedman_mse', init=None,
                                         learning_rate=0.1, loss='deviance',
                                         max_depth=3, max_features=None,
                                         max_leaf_nodes=None,
                                         min_impurity_decrease=0.0,
                                         min_impurity_split=None,
                                         min_samples_leaf=1,
                                         min_samples_split=2,
                                         min_weight_fraction_leaf=0.0,
                                         n_estimators=100,
                                         n_iter_no_change=None,
                                         presort='deprecated', random_state=0,
                                         subsample=1.0, tol=0.0001,
                                         validation_frac

In [ ]:
sel.get_support()

array([False,  True, False, False,  True, False, False,  True,  True,
       False, False, False, False,  True, False, False,  True, False,
       False, False,  True,  True,  True,  True, False, False,  True,
        True, False, False])

In [ ]:
features=x_train.columns[sel.get_support()]

In [ ]:
features

Index(['mean texture', 'mean smoothness', 'mean concave points',
       'mean symmetry', 'area error', 'concavity error', 'worst radius',
       'worst texture', 'worst perimeter', 'worst area', 'worst concavity',
       'worst concave points'],
      dtype='object')

In [ ]:
len(features)

12

In [ ]:
x_train_rfc=sel.transform(x_train)
x_test_rfc=sel.transform(x_test)

In [ ]:
%%time
run(x_train_rfe,x_test_rfe,y_train,y_test)

Accuracy: 0.9736842105263158
CPU times: user 451 ms, sys: 0 ns, total: 451 ms
Wall time: 477 ms


In [ ]:
%%time
run(x_train,x_test,y_train,y_test)

Accuracy: 0.9649122807017544
CPU times: user 410 ms, sys: 63.4 ms, total: 474 ms
Wall time: 476 ms


In [ ]:
for index in range(1,31):
  sel=RFE(GradientBoostingClassifier(n_estimators=100,random_state=0),n_features_to_select=index)
  sel.fit(x_train,y_train)
  x_train_rfe=sel.transform(x_train)
  x_test_rfe=sel.transform(x_test)
  print("Selected Feature:",index)
  run(x_train_rfe,x_test_rfe,y_train,y_test)
  print()

Selected Feature: 1
Accuracy: 0.8771929824561403

Selected Feature: 2
Accuracy: 0.9035087719298246

Selected Feature: 3
Accuracy: 0.9649122807017544

Selected Feature: 4
Accuracy: 0.9736842105263158

Selected Feature: 5
Accuracy: 0.9649122807017544

Selected Feature: 6
Accuracy: 0.9912280701754386

Selected Feature: 7
Accuracy: 0.9736842105263158

Selected Feature: 8
Accuracy: 0.9649122807017544

Selected Feature: 9
Accuracy: 0.9736842105263158

Selected Feature: 10
Accuracy: 0.956140350877193

Selected Feature: 11
Accuracy: 0.956140350877193

Selected Feature: 12
Accuracy: 0.9736842105263158

Selected Feature: 13
Accuracy: 0.956140350877193

Selected Feature: 14
Accuracy: 0.956140350877193

Selected Feature: 15
Accuracy: 0.9649122807017544

Selected Feature: 16
Accuracy: 0.956140350877193

Selected Feature: 17
Accuracy: 0.9649122807017544

Selected Feature: 18
Accuracy: 0.9473684210526315

Selected Feature: 19
Accuracy: 0.9649122807017544

Selected Feature: 20
Accuracy: 0.947368421052

In [ ]:
sel=RFE(GradientBoostingClassifier(n_estimators=100,random_state=0),n_features_to_select=6)
sel.fit(x_train,y_train)
x_train_rfe=sel.transform(x_train)
x_test_rfe=sel.transform(x_test)
print("Selected Feature:",6)
run(x_train_rfe,x_test_rfe,y_train,y_test)
print()


Selected Feature: 6
Accuracy: 0.9912280701754386



In [ ]:
features=x_train.columns[sel.get_support()]
features

Index(['mean concave points', 'area error', 'worst texture', 'worst perimeter',
       'worst area', 'worst concave points'],
      dtype='object')

In [ ]:
for index in range(1,31):
  sel=RFE(GradientBoostingClassifier(n_estimators=100,random_state=0),n_features_to_select=index)
  sel.fit(x_train,y_train)
  x_train_rfe=sel.transform(x_train)
  x_test_rfe=sel.transform(x_test)
  print("Selected Feature:",index)
  run(x_train_rfe,x_test_rfe,y_train,y_test)
  print()

Selected Feature: 1
Accuracy: 0.8771929824561403

Selected Feature: 2
Accuracy: 0.9035087719298246

Selected Feature: 3
Accuracy: 0.9649122807017544

Selected Feature: 4
Accuracy: 0.9736842105263158

Selected Feature: 5
Accuracy: 0.9649122807017544

Selected Feature: 6
Accuracy: 0.9912280701754386

Selected Feature: 7
Accuracy: 0.9736842105263158

Selected Feature: 8
Accuracy: 0.9649122807017544

Selected Feature: 9
Accuracy: 0.9736842105263158

Selected Feature: 10
Accuracy: 0.956140350877193

Selected Feature: 11
Accuracy: 0.956140350877193

Selected Feature: 12
Accuracy: 0.9736842105263158

Selected Feature: 13
Accuracy: 0.956140350877193

Selected Feature: 14
Accuracy: 0.956140350877193

Selected Feature: 15
Accuracy: 0.9649122807017544

Selected Feature: 16
Accuracy: 0.956140350877193

Selected Feature: 17
Accuracy: 0.9649122807017544

Selected Feature: 18
Accuracy: 0.9473684210526315

Selected Feature: 19
Accuracy: 0.9649122807017544

Selected Feature: 20
Accuracy: 0.947368421052